name: Check test suite
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check:
    name: Check outputs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - run: make check
